### ISSUE TITLE
Error: Corrupted meta.xml file.

### ISSUE THREAD

**Issue by Eiskaltereistee** [plesk/ext-uptime-robot#3]
If I try to install the extension, I get the following error:
Corrupted meta.xml file.

Please check this issue, thanks!

**Comment by Kubik-Rubik** [comment]
Hi @Eiskaltereistee!

You cannot install the package that is created automatically by GitHub. Please download the package and unzip it first on your local machine. Then create a new archive so that the manifest file is located in the root of the archive.

Have fun testing the extension. Would love to get some feedback from you!

**Comment by Eiskaltereistee** [comment]
A very nice extension.
But it would be more useful if I'am able to add domain via one click to the uptime robot.

**Comment by Kubik-Rubik** [comment]
Thank you for your suggestion! Please open a new issue so that we do not forget about it. :-)

If you are able to implement it, then a PR is more than welcome! ;-)

**Comment by frankred** [comment]
@Eiskaltereistee I am currently working on that!
